<a href="https://colab.research.google.com/github/Chargers-Team/202270-010-Team-The-Chargers-Project-Development--/blob/main/keras_Sequential.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
data = [7,	1,	2,	1,	7,	1,	2,	7,	1,	2,	7,	1,	2,	1,	2,	7,	1,	2,	1,	2,	1,	2,	7,	1,	2,	1,	2,	7,	1,	2,	1,	2,	4,	6,	1,	2,	4,	6,	2,	1,	7,	1,	2,	7,	1,	2,	7,	1,	2,	1,	2,	7,	1,	2,	0,	1,	1,	2,	1,	1,	3,	2,	1,	1,	1,	2,	1,	3,	7,	9,	7,	9,	1,	7,	9,	1,	2,	3,	1,	2,	0,	1,	2,	1,	2,	1,	4,	1,	7,	2,	1,	3,	2,	1,	3,	1,	7,	2,	3,	1,	1,	3,	2,	2,	1,	3,	2,	1,	3,	2,	1,	1,	1,	4,	1,	1,	2,	3,	10,	12,	4,	1,	1,	2,	3,	10,	12,	2,	1,	3,	10,	12,	1,	2,	1,	2,	1,	2,	1,	2,	7,	1,	2,	1,	2,	1,	2,	1,	2,	1,	7,	1,	1,	2,	1,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	7,	1,	1,	0,	1,	2,	1,	2,	1,	3,	2,	3,	1,	1,	7,	1,	2,	7,	3,	1,	2,	7,	7,	1,	1,	7,	0,	1,	2,	1,	2,	3,	4,	5,	6,	1,	2,	3,	1,	2,	3,	0,	1,	3,	2,	1,	2,	3,	7,	9,	2,	1,	3,	7,	9,	1,	7,	9,	1,	2,	1,	3,	1,	2,	0,	1,	3,	2,	4,	1,	3,	2,	1,	3,	2,	1,	3,	2,	1,	0,	1,	2,	3,	1,	3,	2,	13,	14,	0,	1,	2,	0,	1,	2,	7,	1,	0,	0,	1,	7,	9,	1,	2,	7,	1,	2,	7,	9,	9,	1,	3,	7,	9,	9,	1,	3,	2,	7,	9,	9,	1,	3,	2,	2,	1,	2,	7,	1,	7,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	3,	10,	1,	2,	1,	1,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	8,	9,	9,	9,	0,	1,	1,	3,	3,	0,	1,	3,	1,	3,	1,	3,	1,	3,	0,	1,	1,	3,	1,	3,	1,	0,	2,	1,	2,	0,	4,	6,	1,	3,	2,	1,	2,	0,	7,	1,	7,	0,	1,	2,	0,	2,	1,	0,	1,	0,	1,	2,	3,	3,	1,	2,	13,	14,	0,	1,	4,	6,	7,	1,	0,	1,	3,	2,	1,	3,	1,	7,	7,	1,	2,	1,	2,	1,	1,	2,	4,	7,	1,	4,	1,	0,	1,	1,	3,	2,	1,	2,	1,	2,	0,	1,	3,	1,	3,	3,	1,	1,	0,	2,	1,	3,	7,	8,	8,	0,	1,	7,	1,	2,	1,	7,	1,	3,	1,	0,	1,	2,	0,	1,	7,	0,	2,	1,	3,	7,	0,	7,	1,	2,	10,	1,	2,	3,	4,	1,	2,	1,	0,	2,	4,	1,	2,	4,	1,	2,	0,	1,	2,	0,	4,	1,	7,	10,	6,	11,	0,	4,	1,	7,	10,	6,	11,	0,	7,	2,	0,	2,	1,	3,	7,	0,	1,	0,	1,	2,	0,	2,	1,	2,	1,	1,	0,	1,	0,	7,	1,	2,	1,	10,	11,	0,	1,	10,	11,	0,	1,	3,	2,	10,	11,	3,	1,	2,	10,	1,	0,	1,	0,	1,	0,	1,	0,	1,	2,	3,	0,	1,	2,	3,	7,	4,	1,	1,	3,	2,	2,	2,	0,	1,	2,	1,	1,	7,	1,	0,	4,	1,	4,	1,	0,	1,	10,	11,	1,	7,	1,	0,	2,	1,	7,	1,	0,	1,	0,	1,	2,	0,	7,	1,	0,	7,	1,	2,	3,	0,	0,	7,	0,	7,	0,	1,	2,	3,	0,	1,	7,	0,	1,	3,	2,	0,	1,	0,	1,	0,	1,	3,	2,	3,	1,	2,	1,	3,	2,	1,	3,	2,	2,	2,	1,	0,	2,	0,	0,	3,	1,	0,	3,	2,	0,	1,	7,	1,	0,	2,	1,	3,	2,	1,	2,	2,	2,	1,	0,	2,	1,	2,	1,	2,	1,	2,	1,	0,	2,	4,	2,	7,	8,	1,	1,	2,	1,	2,	1,	2,	1,	0,	2,	4,	1,	4,	1,	3,	4,	1,	1,	0,	0,	7,	9,	0,	1,	2,	1,	0,	0,	2,	1,	1,	2,	4,	7,	1,	3,	1,	0,	2,	1,	0,	2,	3,	2,	2,	1,	0,	2,	1,	7,	9,	9,	1,	0,	2,	7,	9,	1,	0,	2,	1,	0,	2,	0,	1,	2,	7,	9,	7,	9,	1,	0,	0,	1,	2,	1,	0,	2,	1,	2,	3,	1,	2,	3,	1,	0,	2,	0,	1,	2,	3,	0,	1,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	3,	2,	1,	3,	2,	1,	0,	2,	7,	1,	1,	3,	2,	10,	11,	11,	12,	7,	1,	0,	1,	2,	1,	3,	2,	10,	11,	12,	0,	4,	1,	3,	2,	10,	11,	12,	4,	6,	1,	3,	2,	10,	11,	12,	4,	6,	1,	3,	2,	10,	11,	12,	4,	1,	0,	1,	2,	1,	3,	2,	4,	0,	1,	2,	1,	3,	2,	4,	7,	9,	1,	3,	2,	0,	1,	2,	1,	2,	0,	1,	2,	1,	3,	2,	4,	6,	1,	3,	2,	0,	2,	1,	7,	0,	1,	4,	7,	0,	1,	7,	7,	0,	3,	1,	7,	1,	7,	4,	1,	2,	7,	1,	1,	3,	2,	1,	3,	2,	10,	12,	11,	1,	7,	4,	6,	1,	1,	10,	12,	12,	1,	3,	2,	10,	1,	3,	2,	10,	12,	12,	1,	3,	2,	1,	3,	2,	1,	3,	2,	1,	3,	2,	1,	1,	1,	4,	6,	1,	4,	6,	1,	2,	3,	1,	1,	1,	2,	7,	1,	1,	2,	1,	2,	1,	1,	4,	6,	1,	1,	7,	1,	1,	7,	4,	6,	7,	1,	1,	7,	1,	1,	7,	4,	6,	1,	2,	7,	1,	1,	1,	4,	6,	1,	2,	1,	7,	1,	7,	1,	2,	3,	1,	1,	2,	3,	1,	3,	2,	1,	2,	4,	6,	1,	4,	6,	1,	4,	6,	1,	1,	1,	2,	7,	1,	2,	7,	1,	7,	4,	7,	1,	7,	1,	4,	7,	1,	7,	4,	1,	4,	1,	1,	2,	1,	2,	4,	6,	1,	2,	1,	2,	4,	6,	1,	2,	1,	2,	1,	2,	1,	1,	7,	1,	2,	1,	2,	1,	2,	1,	2,	4,	1,	1,	4,	1,	2,	1,	3,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	4,	4,	1,	2,	1,	2,	1,	2,	1,	2,	4,	6,	1,	2,	1,	2,	1,	2,	4,	6,	1,	2,	1,	2,	1,	2,	1,	4,	6,	4,	6,	1,	2,	1,	2,	1,	2,	4,	1,	2,	1,	2,	1,	4,	6,	4,	6,	1,	1,	2,	1,	2,	7,	1,	2,	1,	2,	1,	2,	1,	2,	7,	1,	2,	1,	2,	1,	2,	7,	1,	2,	1,	2,	7,	1,	2,	0,	1,	2,	13,	14,	4,	1,	2,	3,	7,	0,	1,	4,	6,	7,	1,	0,	0,	1,	7,	7,	1,	0,	1,	2,	3,	1,	2,	1,	1,	1,	1,	1,	1,	1,	1,	1,	7,	1,	2,	3,	1,	2,	3,	1,	1,	7,	0,	4,	1,	1,	4,	1,	1,	2,	7,	1,	7,	1,	7,	1,	1,	1,	1,	7,	1,	7,	1,	7,	1,	7,	1,	7,	8,	1,	7,	1,	4,	6,	1,	4,	6,	1,	1,	7,	1,	4,	1,	2,	1,	2,	1,	2,	4,	1,	2,	1,	1,	2,	1,	2,	4,	1,	1,	2,	7,	1,	1,	4,	6,	1,	1,	2,	7,	1,	2,	7,	1,	2,	1,	2,	1,	1,	1,	1,	2,	4,	6,	1,	3,	1,	7,	1,	2,	1,	7,	1,	2,	1,	7,	1,	7,	7,	1,	2,	1,	7,	1,	7,	1,	1,	2,	3,	1,	2,	3,	4,	6,	1,	2,	1,	3,	2,	13,	14,	3,	1,	2,	7,	4,	1,	4,	1,	0,	0,	1,	2,	7,	0,	1,	2,	13,	14,	7,	1,	2,	3,	0,	1,	4,	1,	4,	1,	0,	1,	2,	1,	3,	1,	2,	7,	3,	2,	7,	1,	3,	2,	7,	7,	0,	1,	3,	2,	13,	14,	1,	3,	1,	2,	1,	2,	3,	2,	1,	2,	2,	7,	2,	1,	7,	2,	4,	6,	1,	7,	1,	2,	3,	1,	2,	3,	1,	3,	2,	7,	1,	2,	7,	1,	2,	3,	0,	1,	2,	2,	1,	3,	7,	0,	1,	1,	2,	3,	1,	2,	3,	1,	7,	1,	3,	7,	1,	2,	7,	1,	3,	3,	1,	2,	3,	1,	2,	3,	1,	2,	3,	1,	2,	3,	1,	1,	2,	7,	1,	2,	1,	2,	3,	1,	2,	3,	7,	3,	2,	1,	2,	1,	2,	7,	9,	8,	1,	2,	1,	2,	7,	1,	2,	7,	3,	1,	2,	7,	3,	1,	2,	4,	1,	2,	3,	1,	2,	3,	7,	1,	2,	3,	2,	7,	1,	2,	3,	1,	2,	1,	2,	3,	7,	1,	2,	3,	1,	2,	1,	2,	3,	13,	14,	2,	1,	4,	1,	4,	1,	1,	4,	7,	1,	2,	4,	1,	2,	0,	1,	4,	2,	1,	1,	1,	2,	0,	1,	4,	1,	3,	2,	1,	2,	2,	0,	1,	4,	1,	4,	2,	4,	1,	2,	7,	1,	2,	4,	0,	1,	4,	1,	2,	0,	1,	2,	1,	2,	1,	2,	1,	2,	2,	1,	1,	2,	7,	1,	2,	4,	6,	4,	1,	2,	7,	7,	1,	7,	1,	4,	5,	12,	1,	0,	1,	4,	12,	7,	9,	8,	0,	1,	7,	1,	1,	2,	0,	1,	7,	1,	1,	4,	5,	1,	4,	6,	1,	4,	1,	3,	2,	3,	1,	2,	1,	3,	2,	1,	2,	7,	1,	0,	1,	7,	7,	4,	1,	1,	2,	1,	7,	7,	1,	2,	7,	1,	1,	2,	7,	1,	4,	1,	2,	2,	2,	4,	6,	2,	7,	7,	1,	2,	1,	2,	1,	2,	1,	4,	1,	1,	1,	2,	1,	1,	2,	7,	2,	1,	4,	6,	1,	2,	4,	6,	1,	1,	1,	7,	8,	7,	7,	8,	1,	2,	1,	2,	10,	12,	11,	1,	3,	2,	1,	2,	4,	1,	2,	4,	6,	1,	4,	6,	1,	7,	1,	4,	6,	11,	1,	7,	1,	1,	2,	4,	0,	1,	2,	7,	0,	1,	0,	1,	3,	2,	0,	1,	2,	4,	5,	1,	2,	3,	1,	3,	2,	4,	5,	1,	3,	2,	1,	1,	3,	2,	10,	11,	7,	9,	8,	1,	2,	10,	1,	4,	5,	0,	1,	2,	1,	7,	1,	7,	1,	1,	2,	1,	2,	1,	1,	2,	1,	2,	1,	2,	4,	1,	4,	1,	4,	6,	1,	4,	6,	1,	1,	1,	1,	1,	4,	1,	2,	1,	1,	1,	2,	1,	7,	1,	2,	3,	1,	3,	2,	7,	4,	1,	1,	2,	2,	1,	4,	2,	1,	4,	1,	7,	0,	1,	1,	2,	1,	7,	1,	1,	2,	0,	1,	3,	1,	0,	1,	2,	3,	1,	1,	2,	3,	1,	1,	1,	7,	0,	1,	2,	7,	1,	3,	2,	1,	3,	2,	1,	3,	2,	1,	1,	3,	2,	2,	0,	1,	2,	3,	1,	7,	1,	4,	7,	1,	2,	7,	1,	0,	1,	3,	2,	1,	2,	1,	2,	4,	4,	7,	1,	1,	2,	4,	1,	7,	1,	2,	4,	1,	2,	10,	12,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	1,	2,	4,	1,	2,	1,	2,	2,	10,	4,	1,	2,	1,	2,	1,	2,	1,	2,	3,	10,	12,	1,	2,	3,	10,	1,	2,	10,	11,	1,	2,	10,	12,	1,	2,	10,	12,	4,	1,	2,	3,	10,	12,	11,	4,	6,	1,	2,	1,	2,	3,	10,	12,	11,	4,	6,	1,	2,	1,	2,	3,	10,	12,	11,	3,	1,	2,	1,	2,	3,	10,	12,	11,	3,	1,	2,	1,	2,	3,	10,	12,	11,	3,	1,	2,	3,	1,	2,	1,	2,	3,	10,	12,	11,	3,	1,	2,	4,	1,	3,	2,	1,	2,	4,	6,	1,	2,	3,	10,	12,	11,	4,	6,	1,	2,	3,	10,	12,	11,	3,	1,	2,	4,	1,	2,	3,	10,	12,	11,	4,	1,	2,	3,	10,	12,	11,	4,	1,	2,	3,	10,	12,	11,	4,	6,	1,	2,	10,	12,	11,	1,	7,	8,	9,	3,	2,	10,	11,	12,	10,	11,	12,	7,	2,	1,	4,	7,	1,	4,	1,	2,	4,	7,	1,	2,	7,	9,	2,	3,	1,	7,	2,	3,	1,	7,	7,	1,	2,	3,	4,	2,	3,	1,	7,	2,	3,	1,	7,	4,	7,	1,	2,	3,	10,	11,	1,	7,	1,	2,	3,	1,	2,	4,	2,	3,	1,	7,	2,	3,	1,	7,	7,	2,	1,	4,	7,	1,	4,	1,	2,	4,	7,	1,	2,	7,	2,	3,	1,	7,	2,	3,	1,	7,	7,	1,	2,	3,	4,	2,	3,	1,	7,	2,	3,	1,	7,	4,	7,	2,	1,	3,	10,	12,	11,	1,	7,	1,	2,	3,	1,	2,	4,	2,	3,	1,	7,	2,	3,	1,	7,	7,	1,	7,	1,	4,	7,	1,	4,	1,	2,	4,	7,	1,	2,	7,	2,	3,	1,	7,	2,	3,	1,	7,	7,	1,	2,	3,	4,	2,	3,	1,	7,	2,	3,	1,	7,	4,	7,	1,	2,	3,	10,	11,	1,	7,	1,	2,	3,	1,	2,	4,	2,	3,	1,	7,	2,	3,	1,	7,	1,	2,	3,	10,	1,	2,	1,	2,	1,	2,	3,	1,	2,	1,	2,	3,	10,	12,	11,	3,	1,	2,	10,	12,	11,	1,	2,	10,	12,	11,	1,	2,	3,	1,	2,	3,	10,	12,	11,	2,	1,	3,	1,	2,	10,	12,	0,	1,	1,	1,	2,	3,	1,	1,	2,	0,	1,	1,	2,	1,	1,	0,	1,	1,	2,	1,	7,	1,	1,	1,	2,	3,	1,	2,	3,	7,	1,	1,	1,	2,	3,	1,	7,	1,	2,	3,	1,	2,	7,	1,	2,	3,	1,	0,	1,	1,	1,	7,	1,	2,	1,	2,	1,	1,	1,	0,	0,	7,	1,	3,	2,	7,	9,	4,	1,	2,	3,	1,	3,	2,	7,	10,	1,	3,	2,	1,	3,	2,	10,	11,	1,	10,	1,	2,	1,	1,	2,	3,	1,	0,	0,	1,	7,	9,	1,	2,	7,	1,	2,	1,	1,	1,	2,	3,	1,	0,	0,	1,	0,	1,	3,	2,	0,	7,	10,	0,	10,	0,	1,	2,	0,	1,	3,	0,	1,	2,	0,	1,	0,	1,	2,	3,	0,	1,	2,	0,	10,	12,	0,	0,	7,	9,	9,	1,	2,	0,	1,	3,	0,	7,	10,	11,	4,	0,	10,	12,	7,	8,	0,	1,	2,	3,	0,	1,	3,	0,	7,	1,	13,	14,	1,	2,	13,	1,	7,	9,	7,	9,	7,	9,	7,	9,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	10,	0,	1,	2,	3,	0,	1,	2,	3,	0,	10,	12,	1,	2,	0,	1,	3,	2,	10,	1,	3,	2,	7,	1,	3,	2,	10,	1,	0,	2,	0,	7,	1,	3,	7,	1,	3,	1,	0,	10,	12,	11,	1,	0,	0,	1,	2,	0,	1,	0,	0,	0,	4,	6,	1,	3,	10,	1,	1,	1,	2,	1,	0,	0,	4,	6,	1,	3,	10,	1,	1,	1,	2,	1,	0,	0,	1,	3,	10,	1,	1,	1,	2,	1,	1,	4,	1,	2,	10,	12,	10,	7,	2,	3,	1,	1,	2,	1,	0,	0,	3,	1,	1,	2,	1,	3,	3,	1,	2,	3,	1,	2,	7,	9,	7,	3,	1,	4,	3,	1,	2,	13,	2,	1,	3,	10,	12,	12,	12,	12,	12,	12,	11,	12,	11,	12,	1,	2,	3,	2,	1,	3,	10,	12,	12,	12,	1,	2,	3,	10,	12,	12,	12,	1,	2,	2,	1,	3,	1,	3,	2,	2,	1,	3,	2,	1,	3,	13,	14,	1,	3,	2,	2,	1,	3,	2,	1,	3,	2,	1,	2,	1,	3,	10,	11,	2,	3,	1,	2,	1,	3,	1,	0,	10,	12,	1,	7,	2,	1,	0,	0,	0,	1,	3,	0,	1,	3,	0,	10,	1,	2,	0,	0,	10,	1,	2,	0,	1,	2,	1,	2,	1,	1,	1,	1,	0,	0,	0,	10,	0,	1,	2,	3,	0,	1,	0,	0,	1,	1,	4,	10,	4,	1,	7,	0,	0,	1,	2,	0,	4,	6,	1,	2,	10,	12,	4,	6,	1,	2,	1,	2,	10,	12,	1,	2,	0,	4,	1,	2,	10,	11,	12,	1,	2,	10,	11,	12,	10,	12,	10,	12,	4,	1,	2,	10,	12,	10,	12,	10,	12,	1,	2,	0,	1,	2,	0,	1,	10,	12,	1,	2,	0,	1,	0,	1,	0,	1,	3,	1,	3,	1,	3,	1,	3,	1,	3,	1,	1,	2,	10,	2,	10,	2,	1,	1,	3,	1,	1,	3]
print(data)

In [1]:
data = [7,	1,	2,	1,	7,	1,	2,	7,	1,	2,	7,	1,	2,	1,	2,	7,	1,	2,	1,	2,	1,	2,	7,	1,	2,	1,	2,	7,	1,	2,	1,	2,	4,	6,	1,	2,	4,	6,	2,	1,	7,	1,	2,	7,	1,	2,	7,	1,	2,	1,	2,	7,	1,	2,	0,	1,	1,	2,	1,	1,	3,	2,	1,	1,	1,	2,	1,	3,	7,	9,	7,	9,	1,	7,	9,	1,	2,	3,	1,	2,	0,	1,	2,	1,	2,	1,	4,	1,	7,	2,	1,	3,	2,	1,	3,	1,	7,	2,	3,	1,	1,	3,	2,	2,	1,	3,	2,	1,	3,	2,	1,	1,	1,	4,	1,	1,	2,	3,	10,	12,	4,	1,	1,	2,	3,	10,	12,	2,	1,	3,	10,	12,	1,	2,	1,	2,	1,	2,	1,	2,	7,	1,	2,	1,	2,	1,	2,	1,	2,	1,	7,	1,	1,	2,	1,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	7,	1,	1,	0,	1,	2,	1,	2,	1,	3,	2,	3,	1,	1,	7,	1,	2,	7,	3,	1,	2,	7,	7,	1,	1,	7,	0,	1,	2,	1,	2,	3,	4,	5,	6,	1,	2,	3,	1,	2,	3,	0,	1,	3,	2,	1,	2,	3,	7,	9,	2,	1,	3,	7,	9,	1,	7,	9,	1,	2,	1,	3,	1,	2,	0,	1,	3,	2,	4,	1,	3,	2,	1,	3,	2,	1,	3,	2,	1,	0,	1,	2,	3,	1,	3,	2,	13,	15,	0,	1,	2,	0,	1,	2,	7,	1,	0,	0,	1,	7,	9,	1,	2,	7,	1,	2,	7,	9,	9,	1,	3,	7,	9,	9,	1,	3,	2,	7,	9,	9,	1,	3,	2,	2,	1,	2,	7,	1,	7,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	3,	10,	1,	2,	1,	1,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	8,	9,	9,	9,	0,	1,	1,	3,	3,	0,	1,	3,	1,	3,	1,	3,	1,	3,	0,	1,	1,	3,	1,	3,	1,	0,	2,	1,	2,	0,	4,	6,	1,	3,	2,	1,	2,	0,	7,	1,	7,	0,	1,	2,	0,	2,	1,	0,	1,	0,	1,	2,	3,	3,	1,	2,	13,	15,	0,	1,	4,	6,	7,	1,	0,	1,	3,	2,	1,	3,	1,	7,	7,	1,	2,	1,	2,	1,	1,	2,	4,	7,	1,	4,	1,	0,	1,	1,	3,	2,	1,	2,	1,	2,	0,	1,	3,	1,	3,	3,	1,	1,	0,	2,	1,	3,	7,	8,	8,	0,	1,	7,	1,	2,	1,	7,	1,	3,	1,	0,	1,	2,	0,	1,	7,	0,	2,	1,	3,	7,	0,	7,	1,	2,	10,	1,	2,	3,	4,	1,	2,	1,	0,	2,	4,	1,	2,	4,	1,	2,	0,	1,	2,	0,	4,	1,	7,	10,	6,	11,	0,	4,	1,	7,	10,	6,	11,	0,	7,	2,	0,	2,	1,	3,	7,	0,	1,	0,	1,	2,	0,	2,	1,	2,	1,	1,	0,	1,	0,	7,	1,	2,	1,	10,	11,	0,	1,	10,	11,	0,	1,	3,	2,	10,	11,	3,	1,	2,	10,	1,	0,	1,	0,	1,	0,	1,	0,	1,	2,	3,	0,	1,	2,	3,	7,	4,	1,	1,	3,	2,	2,	2,	0,	1,	2,	1,	1,	7,	1,	0,	4,	1,	4,	1,	0,	1,	10,	11,	1,	7,	1,	0,	2,	1,	7,	1,	0,	1,	0,	1,	2,	0,	7,	1,	0,	7,	1,	2,	3,	0,	0,	7,	0,	7,	0,	1,	2,	3,	0,	1,	7,	0,	1,	3,	2,	0,	1,	0,	1,	0,	1,	3,	2,	3,	1,	2,	1,	3,	2,	1,	3,	2,	2,	2,	1,	0,	2,	0,	0,	3,	1,	0,	3,	2,	0,	1,	7,	1,	0,	2,	1,	3,	2,	1,	2,	2,	2,	1,	0,	2,	1,	2,	1,	2,	1,	2,	1,	0,	2,	4,	2,	7,	8,	1,	1,	2,	1,	2,	1,	2,	1,	0,	2,	4,	1,	4,	1,	3,	4,	1,	1,	0,	0,	7,	9,	0,	1,	2,	1,	0,	0,	2,	1,	1,	2,	4,	7,	1,	3,	1,	0,	2,	1,	0,	2,	3,	2,	2,	1,	0,	2,	1,	7,	9,	9,	1,	0,	2,	7,	9,	1,	0,	2,	1,	0,	2,	0,	1,	2,	7,	9,	7,	9,	1,	0,	0,	1,	2,	1,	0,	2,	1,	2,	3,	1,	2,	3,	1,	0,	2,	0,	1,	2,	3,	0,	1,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	3,	2,	1,	3,	2,	1,	0,	2,	7,	1,	1,	3,	2,	10,	11,	11,	12,	7,	1,	0,	1,	2,	1,	3,	2,	10,	11,	12,	0,	4,	1,	3,	2,	10,	11,	12,	4,	6,	1,	3,	2,	10,	11,	12,	4,	6,	1,	3,	2,	10,	11,	12,	4,	1,	0,	1,	2,	1,	3,	2,	4,	0,	1,	2,	1,	3,	2,	4,	7,	9,	1,	3,	2,	0,	1,	2,	1,	2,	0,	1,	2,	1,	3,	2,	4,	6,	1,	3,	2,	0,	2,	1,	7,	0,	1,	4,	7,	0,	1,	7,	7,	0,	3,	1,	7,	1,	7,	4,	1,	2,	7,	1,	1,	3,	2,	1,	3,	2,	10,	12,	11,	1,	7,	4,	6,	1,	1,	10,	12,	12,	1,	3,	2,	10,	1,	3,	2,	10,	12,	12,	1,	3,	2,	1,	3,	2,	1,	3,	2,	1,	3,	2,	1,	1,	1,	4,	6,	1,	4,	6,	1,	2,	3,	1,	1,	1,	2,	7,	1,	1,	2,	1,	2,	1,	1,	4,	6,	1,	1,	7,	1,	1,	7,	4,	6,	7,	1,	1,	7,	1,	1,	7,	4,	6,	1,	2,	7,	1,	1,	1,	4,	6,	1,	2,	1,	7,	1,	7,	1,	2,	3,	1,	1,	2,	3,	1,	3,	2,	1,	2,	4,	6,	1,	4,	6,	1,	4,	6,	1,	1,	1,	2,	7,	1,	2,	7,	1,	7,	4,	7,	1,	7,	1,	4,	7,	1,	7,	4,	1,	4,	1,	1,	2,	1,	2,	4,	6,	1,	2,	1,	2,	4,	6,	1,	2,	1,	2,	1,	2,	1,	1,	7,	1,	2,	1,	2,	1,	2,	1,	2,	4,	1,	1,	4,	1,	2,	1,	3,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	4,	4,	1,	2,	1,	2,	1,	2,	1,	2,	4,	6,	1,	2,	1,	2,	1,	2,	4,	6,	1,	2,	1,	2,	1,	2,	1,	4,	6,	4,	6,	1,	2,	1,	2,	1,	2,	4,	1,	2,	1,	2,	1,	4,	6,	4,	6,	1,	1,	2,	1,	2,	7,	1,	2,	1,	2,	1,	2,	1,	2,	7,	1,	2,	1,	2,	1,	2,	7,	1,	2,	1,	2,	7,	1,	2,	0,	1,	2,	13,	15,	4,	1,	2,	3,	7,	0,	1,	4,	6,	7,	1,	0,	0,	1,	7,	7,	1,	0,	1,	2,	3,	1,	2,	1,	1,	1,	1,	1,	1,	1,	1,	1,	7,	1,	2,	3,	1,	2,	3,	1,	1,	7,	0,	4,	1,	1,	4,	1,	1,	2,	7,	1,	7,	1,	7,	1,	1,	1,	1,	7,	1,	7,	1,	7,	1,	7,	1,	7,	8,	1,	7,	1,	4,	6,	1,	4,	6,	1,	1,	7,	1,	4,	1,	2,	1,	2,	1,	2,	4,	1,	2,	1,	1,	2,	1,	2,	4,	1,	1,	2,	7,	1,	1,	4,	6,	1,	1,	2,	7,	1,	2,	7,	1,	2,	1,	2,	1,	1,	1,	1,	2,	4,	6,	1,	3,	1,	7,	1,	2,	1,	7,	1,	2,	1,	7,	1,	7,	7,	1,	2,	1,	7,	1,	7,	1,	1,	2,	3,	1,	2,	3,	4,	6,	1,	2,	1,	3,	2,	13,	15,	3,	1,	2,	7,	4,	1,	4,	1,	0,	0,	1,	2,	7,	0,	1,	2,	13,	15,	7,	1,	2,	3,	0,	1,	4,	1,	4,	1,	0,	1,	2,	1,	3,	1,	2,	7,	3,	2,	7,	1,	3,	2,	7,	7,	0,	1,	3,	2,	13,	15,	1,	3,	1,	2,	1,	2,	3,	2,	1,	2,	2,	7,	2,	1,	7,	2,	4,	6,	1,	7,	1,	2,	3,	1,	2,	3,	1,	3,	2,	7,	1,	2,	7,	1,	2,	3,	0,	1,	2,	2,	1,	3,	7,	0,	1,	1,	2,	3,	1,	2,	3,	1,	7,	1,	3,	7,	1,	2,	7,	1,	3,	3,	1,	2,	3,	1,	2,	3,	1,	2,	3,	1,	2,	3,	1,	1,	2,	7,	1,	2,	1,	2,	3,	1,	2,	3,	7,	3,	2,	1,	2,	1,	2,	7,	9,	8,	1,	2,	1,	2,	7,	1,	2,	7,	3,	1,	2,	7,	3,	1,	2,	4,	1,	2,	3,	1,	2,	3,	7,	1,	2,	3,	2,	7,	1,	2,	3,	1,	2,	1,	2,	3,	7,	1,	2,	3,	1,	2,	1,	2,	3,	13,	15,	2,	1,	4,	1,	4,	1,	1,	4,	7,	1,	2,	4,	1,	2,	0,	1,	4,	2,	1,	1,	1,	2,	0,	1,	4,	1,	3,	2,	1,	2,	2,	0,	1,	4,	1,	4,	2,	4,	1,	2,	7,	1,	2,	4,	0,	1,	4,	1,	2,	0,	1,	2,	1,	2,	1,	2,	1,	2,	2,	1,	1,	2,	7,	1,	2,	4,	6,	4,	1,	2,	7,	7,	1,	7,	1,	4,	5,	12,	1,	0,	1,	4,	12,	7,	9,	8,	0,	1,	7,	1,	1,	2,	0,	1,	7,	1,	1,	4,	5,	1,	4,	6,	1,	4,	1,	3,	2,	3,	1,	2,	1,	3,	2,	1,	2,	7,	1,	0,	1,	7,	7,	4,	1,	1,	2,	1,	7,	7,	1,	2,	7,	1,	1,	2,	7,	1,	4,	1,	2,	2,	2,	4,	6,	2,	7,	7,	1,	2,	1,	2,	1,	2,	1,	4,	1,	1,	1,	2,	1,	1,	2,	7,	2,	1,	4,	6,	1,	2,	4,	6,	1,	1,	1,	7,	8,	7,	7,	8,	1,	2,	1,	2,	10,	12,	11,	1,	3,	2,	1,	2,	4,	1,	2,	4,	6,	1,	4,	6,	1,	7,	1,	4,	6,	11,	1,	7,	1,	1,	2,	4,	0,	1,	2,	7,	0,	1,	0,	1,	3,	2,	0,	1,	2,	4,	5,	1,	2,	3,	1,	3,	2,	4,	5,	1,	3,	2,	1,	1,	3,	2,	10,	11,	7,	9,	8,	1,	2,	10,	1,	4,	5,	0,	1,	2,	1,	7,	1,	7,	1,	1,	2,	1,	2,	1,	1,	2,	1,	2,	1,	2,	4,	1,	4,	1,	4,	6,	1,	4,	6,	1,	1,	1,	1,	1,	4,	1,	2,	1,	1,	1,	2,	1,	7,	1,	2,	3,	1,	3,	2,	7,	4,	1,	1,	2,	2,	1,	4,	2,	1,	4,	1,	7,	0,	1,	1,	2,	1,	7,	1,	1,	2,	0,	1,	3,	1,	0,	1,	2,	3,	1,	1,	2,	3,	1,	1,	1,	7,	0,	1,	2,	7,	1,	3,	2,	1,	3,	2,	1,	3,	2,	1,	1,	3,	2,	2,	0,	1,	2,	3,	1,	7,	1,	4,	7,	1,	2,	7,	1,	0,	1,	3,	2,	1,	2,	1,	2,	4,	4,	7,	1,	1,	2,	4,	1,	7,	1,	2,	4,	1,	2,	10,	12,	1,	2,	1,	2,	1,	2,	1,	2,	1,	2,	1,	1,	2,	4,	1,	2,	1,	2,	2,	10,	4,	1,	2,	1,	2,	1,	2,	1,	2,	3,	10,	12,	1,	2,	3,	10,	1,	2,	10,	11,	1,	2,	10,	12,	1,	2,	10,	12,	4,	1,	2,	3,	10,	12,	11,	4,	6,	1,	2,	1,	2,	3,	10,	12,	11,	4,	6,	1,	2,	1,	2,	3,	10,	12,	11,	3,	1,	2,	1,	2,	3,	10,	12,	11,	3,	1,	2,	1,	2,	3,	10,	12,	11,	3,	1,	2,	3,	1,	2,	1,	2,	3,	10,	12,	11,	3,	1,	2,	4,	1,	3,	2,	1,	2,	4,	6,	1,	2,	3,	10,	12,	11,	4,	6,	1,	2,	3,	10,	12,	11,	3,	1,	2,	4,	1,	2,	3,	10,	12,	11,	4,	1,	2,	3,	10,	12,	11,	4,	1,	2,	3,	10,	12,	11,	4,	6,	1,	2,	10,	12,	11,	1,	7,	8,	9,	3,	2,	10,	11,	12,	10,	11,	12,	7,	2,	1,	4,	7,	1,	4,	1,	2,	4,	7,	1,	2,	7,	9,	2,	3,	1,	7,	2,	3,	1,	7,	7,	1,	2,	3,	4,	2,	3,	1,	7,	2,	3,	1,	7,	4,	7,	1,	2,	3,	10,	11,	1,	7,	1,	2,	3,	1,	2,	4,	2,	3,	1,	7,	2,	3,	1,	7,	7,	2,	1,	4,	7,	1,	4,	1,	2,	4,	7,	1,	2,	7,	2,	3,	1,	7,	2,	3,	1,	7,	7,	1,	2,	3,	4,	2,	3,	1,	7,	2,	3,	1,	7,	4,	7,	2,	1,	3,	10,	12,	11,	1,	7,	1,	2,	3,	1,	2,	4,	2,	3,	1,	7,	2,	3,	1,	7,	7,	1,	7,	1,	4,	7,	1,	4,	1,	2,	4,	7,	1,	2,	7,	2,	3,	1,	7,	2,	3,	1,	7,	7,	1,	2,	3,	4,	2,	3,	1,	7,	2,	3,	1,	7,	4,	7,	1,	2,	3,	10,	11,	1,	7,	1,	2,	3,	1,	2,	4,	2,	3,	1,	7,	2,	3,	1,	7,	1,	2,	3,	10,	1,	2,	1,	2,	1,	2,	3,	1,	2,	1,	2,	3,	10,	12,	11,	3,	1,	2,	10,	12,	11,	1,	2,	10,	12,	11,	1,	2,	3,	1,	2,	3,	10,	12,	11,	2,	1,	3,	1,	2,	10,	12,	0,	1,	1,	1,	2,	3,	1,	1,	2,	0,	1,	1,	2,	1,	1,	0,	1,	1,	2,	1,	7,	1,	1,	1,	2,	3,	1,	2,	3,	7,	1,	1,	1,	2,	3,	1,	7,	1,	2,	3,	1,	2,	7,	1,	2,	3,	1,	0,	1,	1,	1,	7,	1,	2,	1,	2,	1,	1,	1,	0,	0,	7,	1,	3,	2,	7,	9,	4,	1,	2,	3,	1,	3,	2,	7,	10,	1,	3,	2,	1,	3,	2,	10,	11,	1,	10,	1,	2,	1,	1,	2,	3,	1,	0,	0,	1,	7,	9,	1,	2,	7,	1,	2,	1,	1,	1,	2,	3,	1,	0,	0,	1,	0,	1,	3,	2,	0,	7,	10,	0,	10,	0,	1,	2,	0,	1,	3,	0,	1,	2,	0,	1,	0,	1,	2,	3,	0,	1,	2,	0,	10,	12,	0,	0,	7,	9,	9,	1,	2,	0,	1,	3,	0,	7,	10,	11,	4,	0,	10,	12,	7,	8,	0,	1,	2,	3,	0,	1,	3,	0,	7,	1,	13,	15,	1,	2,	13,	1,	7,	9,	7,	9,	7,	9,	7,	9,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	1,	2,	0,	10,	0,	1,	2,	3,	0,	1,	2,	3,	0,	10,	12,	1,	2,	0,	1,	3,	2,	10,	1,	3,	2,	7,	1,	3,	2,	10,	1,	0,	2,	0,	7,	1,	3,	7,	1,	3,	1,	0,	10,	12,	11,	1,	0,	0,	1,	2,	0,	1,	0,	0,	0,	4,	6,	1,	3,	10,	1,	1,	1,	2,	1,	0,	0,	4,	6,	1,	3,	10,	1,	1,	1,	2,	1,	0,	0,	1,	3,	10,	1,	1,	1,	2,	1,	1,	4,	1,	2,	10,	12,	10,	7,	2,	3,	1,	1,	2,	1,	0,	0,	3,	1,	1,	2,	1,	3,	3,	1,	2,	3,	1,	2,	7,	9,	7,	3,	1,	4,	3,	1,	2,	13,	2,	1,	3,	10,	12,	12,	12,	12,	12,	12,	11,	12,	11,	12,	1,	2,	3,	2,	1,	3,	10,	12,	12,	12,	1,	2,	3,	10,	12,	12,	12,	1,	2,	2,	1,	3,	1,	3,	2,	2,	1,	3,	2,	1,	3,	13,	15,	1,	3,	2,	2,	1,	3,	2,	1,	3,	2,	1,	2,	1,	3,	10,	11,	2,	3,	1,	2,	1,	3,	1,	0,	10,	12,	1,	7,	2,	1,	0,	0,	0,	1,	3,	0,	1,	3,	0,	10,	1,	2,	0,	0,	10,	1,	2,	0,	1,	2,	1,	2,	1,	1,	1,	1,	0,	0,	0,	10,	0,	1,	2,	3,	0,	1,	0,	0,	1,	1,	4,	10,	4,	1,	7,	0,	0,	1,	2,	0,	4,	6,	1,	2,	10,	12,	4,	6,	1,	2,	1,	2,	10,	12,	1,	2,	0,	4,	1,	2,	10,	11,	12,	1,	2,	10,	11,	12,	10,	12,	10,	12,	4,	1,	2,	10,	12,	10,	12,	10,	12,	1,	2,	0,	1,	2,	0,	1,	10,	12,	1,	2,	0,	1,	0,	1,	0,	1,	3,	1,	3,	1,	3,	1,	3,	1,	3,	1,	1,	2,	10,	2,	10,	2,	1,	1,	3,	1,	1,	3]

In [2]:
import numpy as np
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [16]:
n_steps = 3
X, y = splitSequence(data, n_steps = 3)

In [17]:
print(X)

[[7 1 2]
 [1 2 1]
 [2 1 7]
 ...
 [1 1 3]
 [1 3 1]
 [3 1 1]]


In [18]:
print(y)

[1 7 1 ... 1 1 3]


In [19]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X[:2])

[[[7]
  [1]
  [2]]

 [[1]
  [2]
  [1]]]


In [20]:
%tensorflow_version 2.X
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [21]:
model = tf.keras.Sequential()
model.add(layers.LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(layers.Dense(1))

In [22]:
model.layers

In [23]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_1 (LSTM)               (None, 50)                10400     
                                                                 
 dense_1 (Dense)             (None, 1)                 51        
                                                                 
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=tf.keras.losses.MeanSquaredError(), metrics=['accuracy'])

In [25]:
model.fit(X, y, epochs=200, verbose=1)

Epoch 1/200
89/89 [==============================] - 2s 4ms/step - loss: 9.7352 - accuracy: 0.3324
Epoch 2/200
89/89 [==============================] - 0s 5ms/step - loss: 9.0236 - accuracy: 0.3391
Epoch 3/200
89/89 [==============================] - 0s 4ms/step - loss: 8.7873 - accuracy: 0.3391
Epoch 4/200
89/89 [==============================] - 2s 19ms/step - loss: 8.8353 - accuracy: 0.3391
Epoch 5/200
89/89 [==============================] - 0s 4ms/step - loss: 8.7870 - accuracy: 0.3391
Epoch 6/200
89/89 [==============================] - 0s 4ms/step - loss: 8.6619 - accuracy: 0.3391
Epoch 7/200
89/89 [==============================] - 1s 16ms/step - loss: 8.7092 - accuracy: 0.3391
Epoch 8/200
89/89 [==============================] - 0s 4ms/step - loss: 8.6324 - accuracy: 0.3391
Epoch 9/200
89/89 [==============================] - 0s 6ms/step - loss: 8.5539 - accuracy: 0.3391
Epoch 10/200
89/89 [==============================] - 1s 11ms/step - loss: 8.5354 - accuracy: 0.3391
Epoch 

In [26]:
test_data = np.array([0,1,2])
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[0],
        [1],
        [2]]])

In [27]:
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 172ms/step
[[2.1167123]]


In [28]:
# Final evaluation of the model
scores = model.evaluate(X, y, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Accuracy: 33.73%
